version: 2
main-branch: main
release-branch:
  prefix: release/
  suffix: .x
changelog:
  # Determine which PR changelog options are available and which end up in the changelog
  options:
    type:
      feature: add # that's for backwards compatibility with prevous PRs, remove this option after a release
      breaking: add
      compatible: add
      optimisation: add
      improvement: add
      bugfix: add
      test: skip
      maintenance: skip
      documentation: skip
