/**
 * @fileoverview gRPC-Web generated client stub for cardano.rpc
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.25.3
// source: cardano/rpc/node.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')
const proto = {};
proto.cardano = {};
proto.cardano.rpc = require('./node_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.cardano.rpc.NodeClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.cardano.rpc.NodePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.protobuf.Empty,
 *   !proto.cardano.rpc.CurrentEra>}
 */
const methodDescriptor_Node_GetEra = new grpc.web.MethodDescriptor(
  '/cardano.rpc.Node/GetEra',
  grpc.web.MethodType.UNARY,
  google_protobuf_empty_pb.Empty,
  proto.cardano.rpc.CurrentEra,
  /**
   * @param {!proto.google.protobuf.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cardano.rpc.CurrentEra.deserializeBinary
);


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cardano.rpc.CurrentEra)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cardano.rpc.CurrentEra>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cardano.rpc.NodeClient.prototype.getEra =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cardano.rpc.Node/GetEra',
      request,
      metadata || {},
      methodDescriptor_Node_GetEra,
      callback);
};


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cardano.rpc.CurrentEra>}
 *     Promise that resolves to the response
 */
proto.cardano.rpc.NodePromiseClient.prototype.getEra =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cardano.rpc.Node/GetEra',
      request,
      metadata || {},
      methodDescriptor_Node_GetEra);
};


module.exports = proto.cardano.rpc;

