/**
 * @fileoverview gRPC-Web generated client stub for cardano.rpc
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.25.3
// source: cardano/rpc/node.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as cardano_rpc_node_pb from '../../cardano/rpc/node_pb'; // proto import: "cardano/rpc/node.proto"
import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb'; // proto import: "google/protobuf/empty.proto"


export class NodeClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetEra = new grpcWeb.MethodDescriptor(
    '/cardano.rpc.Node/GetEra',
    grpcWeb.MethodType.UNARY,
    google_protobuf_empty_pb.Empty,
    cardano_rpc_node_pb.CurrentEra,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    cardano_rpc_node_pb.CurrentEra.deserializeBinary
  );

  getEra(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<cardano_rpc_node_pb.CurrentEra>;

  getEra(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: cardano_rpc_node_pb.CurrentEra) => void): grpcWeb.ClientReadableStream<cardano_rpc_node_pb.CurrentEra>;

  getEra(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: cardano_rpc_node_pb.CurrentEra) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/cardano.rpc.Node/GetEra',
        request,
        metadata || {},
        this.methodDescriptorGetEra,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/cardano.rpc.Node/GetEra',
    request,
    metadata || {},
    this.methodDescriptorGetEra);
  }

}

