#!/usr/bin/env bash
# fix-haddock-links.sh
#
# Post-processes Haddock HTML generated by `cabal haddock-project` to fix
# cross-package links. Without this, links to external dependencies are
# broken 404s because the hosted site only contains docs for packages in
# this repo.
#
# Pipeline:
#   1. Prepare: scan filesystem, create symlinks for versioned directories,
#      fetch the CHaP package index, grep HTML for cross-package link
#      targets.
#   2. Resolve + rewrite: for each discovered target, probe candidate
#      doc-site URLs and rewrite HTML links in place (or mark unmapped
#      CHaP packages as unclickable).
#   2b. Re-export rewrite: extract (type, defining package, module) triples
#       from each local page's Haddock-emitted "Source" cabal-store link,
#       then rewrite the local re-export hrefs (e.g. a reference to
#       cardano-ledger-byron's `Address` via `Cardano.Api.Byron`) to point
#       at the upstream doc site instead of the local re-export page.
#   3. Validate + annotate: HEAD each rewritten URL; for dead URLs try to
#      rescue by probing doc-site subdirectories (api/, protocols/,
#      framework/) and parent modules with #t: fragment reconstruction.
#      URLs that can't be rescued become annotated plain-text spans so
#      there are zero clickable 404s.
#
# When dead links are found (unmapped CHaP package or module-level 404),
# the script prints an actionable summary — upstream module name, symbols
# we're linking to, and the referring pages in our own docs — and exits 0
# by default so the docs site can still deploy. Set
# FIX_HADDOCK_LINKS_STRICT=1 to make the script fail instead.
# In GitHub Actions, each dead link also produces a `::warning::`
# annotation visible in the job summary.
#
# Usage: ./scripts/fix-haddock-links.sh <website-directory>

set -euo pipefail

WEBSITE_DIR="${1:?Usage: $0 <website-directory>}"
[ -d "$WEBSITE_DIR" ] || { echo "Error: $WEBSITE_DIR is not a directory" >&2; exit 1; }

TMPFILES=()
trap 'rm -f "${TMPFILES[@]}"' EXIT

mktemp_tracked() {
  local t; t=$(mktemp)
  TMPFILES+=("$t")
  printf '%s\n' "$t"
}

# ============================================================================
# Configuration and helpers
# ============================================================================
#
# For each CHaP package, probe candidate doc-site URLs in order until one
# returns 200 for doc-index.html (a standard Haddock asset every package
# site serves; wrong-site probes reliably 404). Candidate order is:
#   1. Name-suffix subdomain under *.cardano.intersectmbo.org, dropping
#      trailing "-<token>" segments of the package name — fast path for
#      families where the subdomain is a name-suffix (cardano-ledger-*,
#      ouroboros-*, plutus-*).
#   2. IOG_DOC_BASES — known doc-site roots for irregular-subdomain
#      families (cardano-base at base.cardano…, network-mux at
#      ouroboros-network.cardano…, io-classes at input-output-hk.github.io/
#      io-sim, etc.).
#
# Adding a new IOG doc site = one line in IOG_DOC_BASES. Packages on
# existing sites need no edit.

IOG_DOC_BASES=(
  "https://cardano-ledger.cardano.intersectmbo.org"
  "https://base.cardano.intersectmbo.org"
  "https://plutus.cardano.intersectmbo.org/haddock/latest"
  "https://ouroboros-consensus.cardano.intersectmbo.org/haddocks"
  "https://ouroboros-network.cardano.intersectmbo.org"
  "https://input-output-hk.github.io/io-sim"
)

# Some doc sites organise module pages into subdirectories beneath the
# package root (e.g. ouroboros-network publishes Ouroboros-Network-Magic.html
# under ouroboros-network/api/, not ouroboros-network/ directly). When a
# module page URL 404s at the flat path, the rescue logic retries under
# each of these subdirectories.
DOC_SUBDIRS=(api protocols framework)

derive_name_candidates() {
  local name="$1"
  while true; do
    printf '%s\n' "https://${name}.cardano.intersectmbo.org"
    [[ "$name" == *-* ]] || break
    name="${name%-*}"
  done
}

probe_site() {
  local code
  code=$(curl -sI -o /dev/null -w "%{http_code}" --connect-timeout 5 --max-time 10 \
    "${1}/${2}/doc-index.html" 2>/dev/null || echo "000")
  [[ "$code" == "200" || "$code" == "301" || "$code" == "302" ]]
}

resolve_url() {
  local pkg="$1" is_chap="$2" base
  if [[ "$is_chap" != "yes" ]]; then echo "HACKAGE"; return; fi
  while IFS= read -r base; do
    probe_site "$base" "$pkg" && { echo "$base"; return; }
  done < <(derive_name_candidates "$pkg")
  for base in "${IOG_DOC_BASES[@]}"; do
    probe_site "$base" "$pkg" && { echo "$base"; return; }
  done
  echo "NONE"
}

# Append a sed substitution that turns <a href="PATTERN...">X</a> into a
# non-clickable <span class="dead-link" title="TITLE">X</span>, to the
# named script file. We use file-based sed (-f) rather than -e on the
# command line because full-repo builds can produce thousands of
# substitutions whose combined argv hits xargs's limit.
add_unclickable_cmd() {
  local file="$1" href_pattern="$2" title="$3"
  printf 's|<a href="%s[^"]*"[^>]*>\\([^<]*\\)</a>|<span class="dead-link" title="%s">\\1</span>|g\n' \
    "$href_pattern" "$title" >> "$file"
}

# ============================================================================
# Phase 1: Prepare
# ============================================================================

echo "Phase 1: Preparing..."

# Pre-symlink directory set (used to match versioned-hash targets below)
declare -A SHORT_DIRS
for dir in "$WEBSITE_DIR"/*/; do
  SHORT_DIRS["$(basename "$dir")"]=1
done

# Create short-name symlinks for local cabal packages
# (cardano-api-10.26.0.0-inplace -> cardano-api)
symlink_count=0
for dir in "$WEBSITE_DIR"/*/; do
  name="$(basename "$dir")"
  [[ "$name" =~ -inplace-.+ ]] && continue
  if [[ "$name" =~ ^(.+)-[0-9]+\.[0-9]+.*-inplace$ ]]; then
    short="${BASH_REMATCH[1]}"
    if [[ ! -e "$WEBSITE_DIR/$short" ]]; then
      ln -s "$name" "$WEBSITE_DIR/$short"
      symlink_count=$((symlink_count + 1))
    fi
  fi
done

# Post-symlink local-package set (used to skip re-rewriting our own docs)
declare -A LOCAL_SET
for dir in "$WEBSITE_DIR"/*/; do
  [ -d "$dir" ] && LOCAL_SET["$(basename "$dir")"]=1
done

# Fetch CHaP index
CHAP_PKGS_FILE=$(mktemp_tracked)
curl -sL https://chap.intersectmbo.org/01-index.tar.gz \
  | tar -tz | grep -oP '^[^/]+' | sort -u > "$CHAP_PKGS_FILE"
declare -A CHAP_SET
while IFS= read -r pkg; do CHAP_SET["$pkg"]=1; done < "$CHAP_PKGS_FILE"

# Single HTML scan for all cross-package link targets
DISCOVERED_PKGS=$(grep -rohP 'href="\.\./(\.\./)?\K[a-zA-Z][a-zA-Z0-9_.-]*(?=/)' \
                    "$WEBSITE_DIR" 2>/dev/null | sort -u)
discovered_total=$(echo "$DISCOVERED_PKGS" | grep -c . || true)

# Of those targets, symlink versioned-hash names whose stripped base
# matches an existing short directory.
# (href="../base-4.20.2.0-f074/..." + ./base/ exists -> base-4.20.2.0-f074 symlink)
while IFS= read -r target; do
  [ -z "$target" ] && continue
  [[ -e "$WEBSITE_DIR/$target" ]] && continue
  if [[ "$target" =~ ^(.+)-[0-9]+\.[0-9] ]]; then
    short="${BASH_REMATCH[1]}"
    if [[ -v "SHORT_DIRS[$short]" ]]; then
      ln -s "$short" "$WEBSITE_DIR/$target"
      symlink_count=$((symlink_count + 1))
    fi
  fi
done <<< "$DISCOVERED_PKGS"

echo "  Local directories:          ${#LOCAL_SET[@]}"
echo "  CHaP packages:              $(wc -l < "$CHAP_PKGS_FILE")"
echo "  Cross-package link targets: $discovered_total"
echo "  Symlinks created:           $symlink_count"

# ============================================================================
# Phase 2: Resolve doc sites and rewrite links
# ============================================================================

echo "Phase 2: Resolving doc sites and rewriting links..."

REWRITE_SCRIPT=$(mktemp_tracked)
UNMAPPED_CHAP=()   # CHaP packages we couldn't resolve to a doc site — gap in config
NON_CHAP=()        # non-CHaP packages (bootlibs etc.) we don't bother linking to
declare -A PKG_URL=()   # cached doc-site base URL per package (reused in Phase 2b)
skipped=0 rewrote_docsite=0

while IFS= read -r pkg; do
  [ -z "$pkg" ] && continue
  if [[ -v "LOCAL_SET[$pkg]" ]]; then skipped=$((skipped + 1)); continue; fi

  # Haddock emits hrefs to locally-built deps as "<name>-<version>-inplace"
  # even when their docs weren't generated into the output tree (so they're
  # not in LOCAL_SET). Strip the suffix so classification sees the real
  # package name, for cleaner tooltips. Keep the original `pkg` for the sed
  # href pattern, which is what appears in the HTML.
  # NB: ordering matters — evaluate the negative match first so it doesn't
  # clobber BASH_REMATCH[1] set by the capturing regex.
  lookup="$pkg"
  if [[ ! "$pkg" =~ -inplace-.+ ]] && [[ "$pkg" =~ ^(.+)-[0-9]+\.[0-9]+.*-inplace$ ]]; then
    lookup="${BASH_REMATCH[1]}"
  fi
  if [[ "$lookup" != "$pkg" && -v "LOCAL_SET[$lookup]" ]]; then
    skipped=$((skipped + 1)); continue
  fi

  is_chap="no"; [[ -v "CHAP_SET[$lookup]" ]] && is_chap="yes"
  url=$(resolve_url "$lookup" "$is_chap")
  PKG_URL[$lookup]="$url"

  if [[ "$url" == "NONE" ]]; then
    UNMAPPED_CHAP+=("$lookup")
    add_unclickable_cmd "$REWRITE_SCRIPT" "\\.\\./${pkg}/" "No hosted documentation available for ${lookup}"
    add_unclickable_cmd "$REWRITE_SCRIPT" "\\.\\./\\.\\./${pkg}/" "No hosted documentation available for ${lookup}"
    continue
  fi

  if [[ "$url" == "HACKAGE" ]]; then
    # Non-CHaP packages (bootlibs etc.) — don't link to Hackage. The links
    # to base/bytestring/time/... internals are rarely useful to readers of
    # cardano-api docs, and Haddock's per-module URL structure doesn't line
    # up cleanly with Hackage's rendering, so we'd mostly generate 404s.
    # Leave the symbol visible but unclickable.
    NON_CHAP+=("$lookup")
    add_unclickable_cmd "$REWRITE_SCRIPT" "\\.\\./${pkg}/" "${lookup} is not a CHaP package; docs not linked"
    add_unclickable_cmd "$REWRITE_SCRIPT" "\\.\\./\\.\\./${pkg}/" "${lookup} is not a CHaP package; docs not linked"
    continue
  fi

  target="${url}/${lookup}/"
  rewrote_docsite=$((rewrote_docsite + 1))
  printf 's|href="\\.\\./%s/|href="%s|g\n' "$pkg" "$target" >> "$REWRITE_SCRIPT"
  printf 's|href="\\.\\./\\.\\./%s/|href="%s|g\n' "$pkg" "$target" >> "$REWRITE_SCRIPT"
done <<< "$DISCOVERED_PKGS"

echo "  Local (skipped):        $skipped"
echo "  Rewritten (doc site):   $rewrote_docsite"
echo "  Non-CHaP (unclickable): ${#NON_CHAP[@]}"
echo "  Unmapped CHaP:          ${#UNMAPPED_CHAP[@]}"
if [[ ${#UNMAPPED_CHAP[@]} -gt 0 ]]; then
  printf '    - %s\n' "${UNMAPPED_CHAP[@]}"
fi

if [[ -s "$REWRITE_SCRIPT" ]]; then
  find "$WEBSITE_DIR" -name '*.html' -print0 | xargs -0 -P "$(nproc)" sed -i -f "$REWRITE_SCRIPT"
fi

# ============================================================================
# Phase 2b: Rewrite re-exported type links to the original defining package
# ============================================================================
#
# Haddock resolves re-exports to the LOCAL re-export page (e.g. a reference
# to cardano-ledger-byron's `Address` via `Cardano.Api.Byron` becomes
# href="Cardano-Api-Byron.html#t:Address", not an external link). The
# Haddock-emitted "Source" link, however, points to the cabal store for the
# original defining package (file:///.../.cabal/store/PKG-VERSION/.../src/
# Module.Name.html). We use that as the source of truth to rewrite these
# local re-export hrefs to point at the upstream doc site.

echo "Phase 2b: Rewriting re-exported type links..."

REEXPORTS_FILE=$(mktemp_tracked)
python3 - "$WEBSITE_DIR" <<'PYEOF' > "$REEXPORTS_FILE"
import os, re, sys
website = sys.argv[1]
pattern = re.compile(
    r'id="(t|v):([^"]+)" class="def">[^<]*</a>\s*<a href="file:///[^"]*?/([a-zA-Z][\w-]*)-\d+\.[^/]*/share/doc/html/src/([^"#]+)\.html'
)
for d in os.listdir(website):
    if not d.endswith('-inplace') or not os.path.isdir(os.path.join(website, d)):
        continue
    dir_path = os.path.join(website, d)
    for f in os.listdir(dir_path):
        if not f.endswith('.html'):
            continue
        html = open(os.path.join(dir_path, f)).read()
        for m in pattern.finditer(html):
            atype, name, pkg, source_module = m.groups()
            module_page = source_module.replace('.', '-') + '.html'
            # Tab-separated: local_page, anchor, name, package, module_page
            print('\t'.join([f, atype, name, pkg, module_page]))
PYEOF

reexport_total=$(wc -l < "$REEXPORTS_FILE" | tr -d ' ')
echo "  Re-exports found: $reexport_total"

reexport_rewritten=0
reexport_unresolvable=0
if [[ $reexport_total -gt 0 ]]; then
  # Build candidate URLs: direct, then subdirs, then parent-stripped (with subdirs).
  # Format: local_page \t anchor \t name \t candidate_url
  REEXPORT_CANDIDATES=$(mktemp_tracked)
  while IFS=$'\t' read -r local_page anchor name pkg module_page; do
    [ -z "$local_page" ] && continue

    # Resolve package base URL via the Phase 2 cache (fall back to resolve_url
    # for packages not seen as cross-package targets in the HTML).
    if [[ -v "PKG_URL[$pkg]" ]]; then
      base="${PKG_URL[$pkg]}"
    else
      is_chap="no"; [[ -v "CHAP_SET[$pkg]" ]] && is_chap="yes"
      base=$(resolve_url "$pkg" "$is_chap")
      PKG_URL[$pkg]="$base"
    fi

    # Skip unresolvable (NONE) and non-CHaP (HACKAGE — we don't link there).
    [[ "$base" == "NONE" || "$base" == "HACKAGE" ]] && continue

    # Direct URL
    echo "${local_page}	${anchor}	${name}	${base}/${pkg}/${module_page}" >> "$REEXPORT_CANDIDATES"

    # Subdirectory variants (ouroboros-network layout)
    for subdir in "${DOC_SUBDIRS[@]}"; do
      echo "${local_page}	${anchor}	${name}	${base}/${pkg}/${subdir}/${module_page}" >> "$REEXPORT_CANDIDATES"
    done

    # Progressively stripped parent modules (+ subdir variants)
    module_base="${module_page%.html}"
    while [[ "$module_base" == *-* ]]; do
      module_base="${module_base%-*}"
      echo "${local_page}	${anchor}	${name}	${base}/${pkg}/${module_base}.html" >> "$REEXPORT_CANDIDATES"
      for subdir in "${DOC_SUBDIRS[@]}"; do
        echo "${local_page}	${anchor}	${name}	${base}/${pkg}/${subdir}/${module_base}.html" >> "$REEXPORT_CANDIDATES"
      done
    done
  done < "$REEXPORTS_FILE"

  # Probe all unique candidate URLs in parallel
  REEXPORT_VALID_FILE=$(mktemp_tracked)
  if [[ -s "$REEXPORT_CANDIDATES" ]]; then
    # shellcheck disable=SC2016
    awk -F'\t' '{print $4}' "$REEXPORT_CANDIDATES" | sort -u | \
      xargs -P 16 -I{} sh -c \
        'code=$(curl -sI -o /dev/null -w "%{http_code}" --connect-timeout 5 --max-time 10 "{}"); if [ "$code" = "200" ] || [ "$code" = "301" ] || [ "$code" = "302" ]; then echo "{}"; fi' \
        > "$REEXPORT_VALID_FILE" 2>/dev/null
  fi

  declare -A REEXPORT_VALID_SET=()
  while IFS= read -r url; do
    [ -z "$url" ] && continue
    REEXPORT_VALID_SET["$url"]=1
  done < "$REEXPORT_VALID_FILE"

  # For each re-export, walk its candidates in order and pick the first
  # that validated. First-hit-wins prefers the direct URL over subdir /
  # parent fallbacks.
  declare -A REEXPORT_RESOLVED=()   # "local_page|anchor|name" -> resolved_url
  while IFS=$'\t' read -r local_page anchor name candidate; do
    [ -z "$local_page" ] && continue
    key="${local_page}|${anchor}|${name}"
    [[ -v "REEXPORT_RESOLVED[$key]" ]] && continue
    if [[ -v "REEXPORT_VALID_SET[$candidate]" ]]; then
      REEXPORT_RESOLVED["$key"]="$candidate"
    fi
  done < "$REEXPORT_CANDIDATES"

  # Build sed rewrite rules. We only rewrite the exact
  # href="LOCAL_PAGE#ANCHOR:NAME" that we've proven is a re-export of a
  # type documented at a reachable upstream URL; the LOCAL_PAGE#ANCHOR:NAME
  # for local-only types (e.g. cardano-api's own Address GADT) is left
  # untouched.
  REEXPORT_SCRIPT=$(mktemp_tracked)
  for key in "${!REEXPORT_RESOLVED[@]}"; do
    IFS='|' read -r local_page anchor name <<< "$key"
    resolved="${REEXPORT_RESOLVED[$key]}"
    escaped_local=$(printf '%s' "$local_page" | sed 's|[&/\]|\\&|g; s|\.|\\.|g')
    escaped_resolved=$(printf '%s' "$resolved" | sed 's|[&/\]|\\&|g')
    printf 's|href="%s#%s:%s"|href="%s#%s:%s"|g\n' \
      "$escaped_local" "$anchor" "$name" "$escaped_resolved" "$anchor" "$name" \
      >> "$REEXPORT_SCRIPT"
    reexport_rewritten=$((reexport_rewritten + 1))
  done
  reexport_unresolvable=$((reexport_total - reexport_rewritten))

  if [[ -s "$REEXPORT_SCRIPT" ]]; then
    find "$WEBSITE_DIR" -name '*.html' -print0 | xargs -0 -P "$(nproc)" sed -i -f "$REEXPORT_SCRIPT"
  fi
fi

echo "  Rewritten:    $reexport_rewritten"
echo "  Unresolvable: $reexport_unresolvable"

# ============================================================================
# Phase 3: Validate external URLs and annotate dead ones
# ============================================================================

echo "Phase 3: Validating external URLs..."

URLS_FILE=$(mktemp_tracked)
DEAD_URLS_FILE=$(mktemp_tracked)
grep -rohP 'href="\Khttps://[^"#]+\.html' "$WEBSITE_DIR" 2>/dev/null | sort -u > "$URLS_FILE"
url_count=$(wc -l < "$URLS_FILE")

if [[ $url_count -gt 0 ]]; then
  # shellcheck disable=SC2016 # single quotes intentional: expansions evaluated by inner sh -c
  xargs -P 16 -I{} sh -c \
    'code=$(curl -sI -o /dev/null -w "%{http_code}" --connect-timeout 5 --max-time 10 "{}"); if [ "$code" != "200" ] && [ "$code" != "301" ] && [ "$code" != "302" ]; then echo "{}"; fi' \
    < "$URLS_FILE" > "$DEAD_URLS_FILE" 2>/dev/null
fi
dead_count=$(wc -l < "$DEAD_URLS_FILE" | tr -d ' ')

# Phase 3a: rescue dead URLs by probing doc-site subdirectories (e.g.
# ouroboros-network/api/) and parent modules. Haddock frequently links to
# internal defining modules that don't publish as standalone pages — the
# type is actually documented on a parent module (stripping the last
# dash-separated segment). When we find a valid parent, we rewrite the
# link to <parent>#t:<LastComponent> so the browser still scrolls to the
# type definition instead of showing a greyed-out span.
declare -A DEAD_TO_RESCUE=() DEAD_TO_FRAGMENT=()
rescued_count=0
if [[ $dead_count -gt 0 ]]; then
  RESCUE_CANDIDATES=$(mktemp_tracked)
  while IFS= read -r dead_url; do
    [ -z "$dead_url" ] && continue
    base_path="${dead_url%/*}"
    module_file=$(basename "$dead_url" .html)

    # Subdirectory variants at the same level. Use the last dash-component
    # of the module name as the fragment suffix — harmless if the browser
    # doesn't find it, useful for links emitted without a #fragment.
    stripped_first="${module_file##*-}"
    for subdir in "${DOC_SUBDIRS[@]}"; do
      echo "${dead_url}	${base_path}/${subdir}/${module_file}.html	${stripped_first}" >> "$RESCUE_CANDIDATES"
    done

    # Progressively stripped parent modules (+ subdir variants).
    remaining="$module_file"
    parent_stripped_first=""
    while [[ "$remaining" == *-* ]]; do
      last="${remaining##*-}"
      remaining="${remaining%-*}"
      [[ -z "$parent_stripped_first" ]] && parent_stripped_first="$last"
      echo "${dead_url}	${base_path}/${remaining}.html	${parent_stripped_first}" >> "$RESCUE_CANDIDATES"
      for subdir in "${DOC_SUBDIRS[@]}"; do
        echo "${dead_url}	${base_path}/${subdir}/${remaining}.html	${parent_stripped_first}" >> "$RESCUE_CANDIDATES"
      done
    done
  done < "$DEAD_URLS_FILE"

  RESCUE_VALID_FILE=$(mktemp_tracked)
  if [[ -s "$RESCUE_CANDIDATES" ]]; then
    # shellcheck disable=SC2016
    awk -F'\t' '{print $2}' "$RESCUE_CANDIDATES" | sort -u | \
      xargs -P 16 -I{} sh -c \
        'code=$(curl -sI -o /dev/null -w "%{http_code}" --connect-timeout 5 --max-time 10 "{}"); if [ "$code" = "200" ] || [ "$code" = "301" ] || [ "$code" = "302" ]; then echo "{}"; fi' \
        > "$RESCUE_VALID_FILE" 2>/dev/null
  fi

  declare -A RESCUE_VALID_SET=()
  while IFS= read -r url; do
    [ -z "$url" ] && continue
    RESCUE_VALID_SET["$url"]=1
  done < "$RESCUE_VALID_FILE"

  # First-match-wins: direct subdir hit preferred over deeper parents.
  while IFS=$'\t' read -r dead cand stripped; do
    [ -z "$dead" ] && continue
    [[ -v "DEAD_TO_RESCUE[$dead]" ]] && continue
    if [[ -v "RESCUE_VALID_SET[$cand]" ]]; then
      DEAD_TO_RESCUE["$dead"]="$cand"
      DEAD_TO_FRAGMENT["$dead"]="$stripped"
    fi
  done < "$RESCUE_CANDIDATES"

  rescued_count=${#DEAD_TO_RESCUE[@]}

  if [[ $rescued_count -gt 0 ]]; then
    RESCUE_SCRIPT=$(mktemp_tracked)
    for dead in "${!DEAD_TO_RESCUE[@]}"; do
      rescue="${DEAD_TO_RESCUE[$dead]}"
      stripped="${DEAD_TO_FRAGMENT[$dead]}"
      escaped_dead=$(printf '%s' "$dead" | sed 's|[&/\]|\\&|g; s|\.|\\.|g')
      escaped_rescue=$(printf '%s' "$rescue" | sed 's|[&/\]|\\&|g')
      # href="DEAD"      -> href="RESCUE#t:<stripped>"  (bare URL, add fragment)
      # href="DEAD#frag" -> href="RESCUE#frag"           (preserve fragment)
      printf 's|href="%s"|href="%s#t:%s"|g\n' \
        "$escaped_dead" "$escaped_rescue" "$stripped" >> "$RESCUE_SCRIPT"
      printf 's|href="%s#|href="%s#|g\n' \
        "$escaped_dead" "$escaped_rescue" >> "$RESCUE_SCRIPT"
    done
    find "$WEBSITE_DIR" -name '*.html' -print0 | xargs -0 -P "$(nproc)" sed -i -f "$RESCUE_SCRIPT"
  fi
fi

dead_remaining=$((dead_count - rescued_count))

echo "  URLs checked: $url_count"
echo "  Valid:        $((url_count - dead_count))"
echo "  Dead:         $dead_count"
echo "  Rescued:      $rescued_count"
echo "  Unrescuable:  $dead_remaining"

# Per-URL context tables, populated BEFORE the <a>→<span> replacement so
# the original anchor text and reference sites are still in the HTML.
declare -A DEAD_PKG DEAD_MODULE DEAD_SYMBOLS DEAD_REFS

DEAD_SCRIPT=$(mktemp_tracked)
if [[ $dead_remaining -gt 0 ]]; then
  while IFS= read -r dead_url; do
    [ -z "$dead_url" ] && continue
    # Rescued URLs have already been rewritten; no unclickable annotation.
    [[ -v "DEAD_TO_RESCUE[$dead_url]" ]] && continue

    # Package + Haskell module name (Haddock encodes dots as dashes)
    if [[ "$dead_url" == *"hackage.haskell.org"* ]]; then
      pkg=$(echo "$dead_url" | grep -oP 'package/\K[^/]+')
    else
      pkg=$(echo "$dead_url" | grep -oP '[^/]+(?=/[^/]+\.html$)')
    fi
    module_file=$(basename "$dead_url" .html)
    DEAD_PKG[$dead_url]="$pkg"
    DEAD_MODULE[$dead_url]="${module_file//-/.}"

    # Symbols the dead URL is trying to link to (text of each <a> tag)
    regex_url=$(printf '%s' "$dead_url" | sed 's|[][\\.^$*+?{}|()]|\\&|g')
    DEAD_SYMBOLS[$dead_url]=$(grep -rohP \
      "<a[^>]*href=\"${regex_url}[^\"]*\"[^>]*>\\K[^<]+" "$WEBSITE_DIR" 2>/dev/null \
      | sort -u | head -8 | paste -sd ', ' || echo "")

    # Our own docs pages that reference it (the re-export sites we ship)
    DEAD_REFS[$dead_url]=$(grep -rlF "$dead_url" "$WEBSITE_DIR" 2>/dev/null \
      | sed "s|^${WEBSITE_DIR}/||" | sort -u | head -6 || echo "")

    echo "    - $dead_url ($pkg)"
    escaped=$(printf '%s' "$dead_url" | sed 's|[&/\]|\\&|g; s|\.|\\.|g')
    add_unclickable_cmd "$DEAD_SCRIPT" "$escaped" \
      "From ${pkg} — documentation not available at the expected URL"
  done < "$DEAD_URLS_FILE"
  if [[ -s "$DEAD_SCRIPT" ]]; then
    find "$WEBSITE_DIR" -name '*.html' -print0 | xargs -0 -P "$(nproc)" sed -i -f "$DEAD_SCRIPT"
  fi
fi

# Inject dead-link CSS whenever any <span class="dead-link"> was produced
if [[ ${#UNMAPPED_CHAP[@]} -gt 0 || ${#NON_CHAP[@]} -gt 0 || $dead_count -gt 0 ]]; then
  find "$WEBSITE_DIR" -name '*.html' -print0 | xargs -0 -P "$(nproc)" sed -i \
    's|</head>|<style>.dead-link { border-bottom: 1px dotted \#888; color: \#888; cursor: help; }</style></head>|'
fi

# ============================================================================
# Summary + strict-mode exit
# ============================================================================

echo ""
echo "=== fix-haddock-links summary ==="
echo "  Discovered:             $discovered_total"
echo "  Local (skipped):        $skipped"
echo "  Rewritten (doc site):   $rewrote_docsite"
echo "  Re-exports rewritten:   $reexport_rewritten"
echo "  Re-exports unresolved:  $reexport_unresolvable"
echo "  Non-CHaP (unclickable): ${#NON_CHAP[@]}"
echo "  Unmapped CHaP:          ${#UNMAPPED_CHAP[@]}"
echo "  URLs validated:         $url_count"
echo "  Dead links rescued:     $rescued_count"
echo "  Dead links annotated:   $dead_remaining"
echo "================================="

total_dead=$(( ${#UNMAPPED_CHAP[@]} + dead_remaining ))
if [[ $total_dead -eq 0 ]]; then
  exit 0
fi

echo ""
echo "=== fix-haddock-links: dead links detected ==="

if [[ ${#UNMAPPED_CHAP[@]} -gt 0 ]]; then
  echo ""
  echo "Unresolvable CHaP packages (${#UNMAPPED_CHAP[@]}):"
  for pkg in "${UNMAPPED_CHAP[@]}"; do
    echo "  - $pkg"
    [[ -n "${GITHUB_ACTIONS:-}" ]] && \
      echo "::warning title=Unmapped CHaP package::$pkg has no known doc site. Add its base URL to IOG_DOC_BASES in scripts/fix-haddock-links.sh."
  done
  echo ""
  echo "  Fix: find the package's published Haddocks (check its source repo for"
  echo "       a gh-pages or CloudFront deployment), then append the base URL"
  echo "       to IOG_DOC_BASES in scripts/fix-haddock-links.sh and re-run."
fi

if [[ $dead_remaining -gt 0 ]]; then
  echo ""
  echo "Module-level 404s (${dead_remaining}):"
  while IFS= read -r dead_url; do
    [ -z "$dead_url" ] && continue
    # Skip rescued URLs — they were rewritten, not annotated.
    [[ -v "DEAD_TO_RESCUE[$dead_url]" ]] && continue
    echo ""
    echo "  $dead_url"
    echo "    Upstream: ${DEAD_MODULE[$dead_url]} (in package ${DEAD_PKG[$dead_url]})"
    [[ -n "${DEAD_SYMBOLS[$dead_url]:-}" ]] && \
      echo "    Symbols we link to: ${DEAD_SYMBOLS[$dead_url]}"
    if [[ -n "${DEAD_REFS[$dead_url]:-}" ]]; then
      echo "    Linked from our docs:"
      while IFS= read -r ref; do
        [ -z "$ref" ] && continue
        echo "      - $ref"
      done <<< "${DEAD_REFS[$dead_url]}"
    fi
    [[ -n "${GITHUB_ACTIONS:-}" ]] && \
      echo "::warning title=Dead haddock link::${DEAD_MODULE[$dead_url]} (in ${DEAD_PKG[$dead_url]}) returned 404 at $dead_url"
  done < "$DEAD_URLS_FILE"
  echo ""
  echo "  Fix:"
  echo "    1. Visit the upstream doc site and search for the module name."
  echo "       If it's been renamed, moved, or removed, our re-exports or"
  echo "       dependency bounds are out of date."
  echo "    2. The 'Linked from' HTML paths mirror our Haskell module layout"
  echo "       (e.g. cardano-api/Cardano-Api-Ledger.html corresponds to the"
  echo "       source module Cardano.Api.Ledger). Open those .hs files and"
  echo "       grep for the listed symbols to find the re-export site."
  echo "    3. If a dep bound is pinned to a version whose module layout"
  echo "       doesn't match the published docs, bump it."
  echo "    4. Otherwise the links are already annotated as greyed-out spans"
  echo "       with tooltips — no action needed if that's acceptable."
fi

echo ""
if [[ "${FIX_HADDOCK_LINKS_STRICT:-0}" == "1" ]]; then
  echo "FIX_HADDOCK_LINKS_STRICT=1 — exiting 1."
  exit 1
fi
echo "Exiting 0 (warn-only default). Set FIX_HADDOCK_LINKS_STRICT=1 to fail the build."
exit 0
