name: Check HLint

on:
  merge_group:
  pull_request:

jobs:
  check-hlint:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

    - uses: actions/checkout@v3

    - uses: haskell-actions/hlint-scan@v1
