name: Check HLint

on:
  merge_group:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get -y install libtinfo5

    - name: 'Set up HLint'
      uses: rwe/actions-hlint-setup@v1
      with:
        version: 3.3

    - name: 'Run HLint'
      uses: rwe/actions-hlint-run@v2
