name: Check changelog fragments

on:
  merge_group:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  check-changelog:
    if: ${{ github.event_name != 'merge_group' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
            substituters = https://cache.iog.io/ https://cache.nixos.org/

      - uses: input-output-hk/cardano-dev/herald/.github/actions/validate@mgalazyn/release-tool
        with:
          version: github:input-output-hk/cardano-dev/mgalazyn/release-tool
