name: "Update github pages"

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
            substituters = https://cache.iog.io/ https://cache.nixos.org/

      - uses: rrbutani/use-nix-shell-action@v1

      - name: Update cabal indices
        run: |
          cabal update

      - name: Build whole project
        run: |
          cabal build all

      - name: Build haddock documentation
        run: |
          mkdir website
          cabal haddock-project --output=./website --internal --foreign-libraries

      - name: Build typedoc documentation
        run: |
          nix build .#wasm-typedoc
          mkdir -p website/cardano-wasm/typedoc
          cp -r result/. website/cardano-wasm/typedoc/

      - name: Compress website
        run: |
          tar -czf website.tgz -C website .

      - name: Upload website artifact
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        continue-on-error: true
        with:
          name: website
          path: ./website.tgz

      - name: Deploy documentation to gh-pages 🚀
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN || github.token }}
          publish_dir: website
          cname: cardano-api.cardano.intersectmbo.org
          force_orphan: true
